# Generated by Django 6.0.6 on 2026-06-22 14:12

import catalog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('slug', models.SlugField(help_text="Versione URL del nome (es. 'chitarre-elettriche')", unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Prodotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=200)),
                ('descrizione', models.TextField()),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condizione', models.CharField(choices=[('nuovo', 'Nuovo'), ('usato_ottimo', 'Usato - Come Nuovo'), ('usato_buono', 'Usato - Buone Condizioni'), ('usato_accettabile', 'Usato - Accettabile'), ('da_riparare', 'Non Funzionante / Da Riparare')], default='usato_buono', max_length=20)),
                ('disponibile', models.BooleanField(default=True, help_text="Togli la spunta se l'oggetto è stato venduto")),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('data_modifica', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prodotti', to='catalog.categoria')),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prodotti_in_vendita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inserimento'],
            },
        ),
        migrations.CreateModel(
            name='ImmagineProdotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immagine', models.ImageField(upload_to=catalog.models.path_foto_prodotto)),
                ('principale', models.BooleanField(default=False, help_text='Usa come foto copertina')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='immagini', to='catalog.prodotto')),
            ],
            options={
                'verbose_name_plural': 'Immagini Prodotti',
            },
        ),
    ]
