# Generated by Django 6.0.6 on 2026-06-22 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='categoria_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sottocategorie', to='catalog.categoria'),
        ),
        migrations.AddField(
            model_name='prodotto',
            name='strumento_riferimento',
            field=models.CharField(choices=[('sax', 'Sassofono'), ('chitarra_el', 'Chitarra Elettrica'), ('chitarra_ac', 'Chitarra Acustica'), ('basso', 'Basso Elettrico'), ('piano', 'Pianoforte e Tastiere'), ('batteria', 'Batteria e Percussioni'), ('fiati_altri', 'Altri Fiati (Tromba, Flauto, ecc.)'), ('universale', 'Universale / Non specifico')], default='universale', help_text="Seleziona lo strumento a cui è destinato questo prodotto. Scegli 'Universale' se va bene per tutti.", max_length=50),
            preserve_default=False,
        ),
    ]
