# Generated by Django 6.0.6 on 2026-06-23 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_tag_prodotto_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prodotto',
            name='strumento_riferimento',
        ),
    ]
