# Generated by Django 6.0.6 on 2026-06-23 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_prodotto_strumento_riferimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condizione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Condizioni',
            },
        ),
        migrations.RemoveField(
            model_name='prodotto',
            name='tag',
        ),
        migrations.AlterField(
            model_name='prodotto',
            name='condizione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prodotti', to='catalog.condizione'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
