# Generated by Django 6.0.6 on 2026-06-23 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_categoria_slug_alter_prodotto_prezzo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('aggiornato_il', models.DateTimeField(auto_now=True)),
                ('utente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrello', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoCarrello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantita', models.PositiveIntegerField(default=1)),
                ('aggiunto_il', models.DateTimeField(auto_now_add=True)),
                ('carrello', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='cart.carrello')),
                ('prodotto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.prodotto')),
            ],
            options={
                'unique_together': {('carrello', 'prodotto')},
            },
        ),
    ]
