# Generated by Django 6.0.6 on 2026-06-23 16:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('catalog', '0006_alter_categoria_slug_alter_prodotto_prezzo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=100)),
                ('indirizzo', models.CharField(max_length=250)),
                ('citta', models.CharField(max_length=100)),
                ('cap', models.CharField(max_length=10)),
                ('totale', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creato_il', models.DateTimeField(auto_now_add=True)),
                ('utente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoOrdine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prezzo_pagato', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prodotto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.prodotto')),
                ('ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elementi', to='cart.ordine')),
            ],
        ),
    ]
