# Generated by Django 6.0.6 on 2026-06-18 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilo',
            name='citta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profilo',
            name='eta',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
