# Generated by Django 6.0.6 on 2026-06-19 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profilo_citta_profilo_eta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='profilo',
            name='foto_profilo',
            field=models.ImageField(blank=True, null=True, upload_to='foto_profilo/'),
        ),
        migrations.AlterField(
            model_name='profilo',
            name='eta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profilo',
            name='ruolo',
            field=models.CharField(choices=[('acquirente', 'Acquirente'), ('venditore', 'Venditore')], default='acquirente', max_length=20),
        ),
        migrations.AlterField(
            model_name='profilo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
