# Generated by Django 6.0.6 on 2026-06-18 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profilo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruolo', models.CharField(choices=[('ACQUIRENTE', 'Utente Registrato - Acquirente'), ('VENDITORE', 'Utente Registrato - Venditore')], default='ACQUIRENTE', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profilo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
