# Generated by Django 6.0.6 on 2026-06-22 14:12

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profilo_foto_profilo_alter_profilo_eta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilo',
            name='foto_profilo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.path_foto_profilo),
        ),
    ]
