# Generated by Django 6.0.6 on 2026-06-23 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_ordine_elementoordine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordine',
            name='utente',
        ),
        migrations.DeleteModel(
            name='ElementoOrdine',
        ),
        migrations.DeleteModel(
            name='Ordine',
        ),
    ]
