# Generated by Django 6.0.6 on 2026-06-23 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_ordine_utente_delete_elementoordine_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('testo', models.TextField()),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
                ('acquirente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_scritte', to=settings.AUTH_USER_MODEL)),
                ('venditore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recensioni_ricevute', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
